
services:
  postgres:
    image: postgres:17
    container_name: swe_deep
    restart: unless-stopped
    environment:
      POSTGRES_USER: aiarnob23
      POSTGRES_PASSWORD: aiarnob23
      POSTGRES_DB: swe_deep
    ports:
      - "6668:5432" 
    volumes:
      - swe_deep:/var/lib/postgresql/data
    networks:
      - swe_deep

networks:
  swe_deep:
    driver: bridge
    name: swe_deep

volumes:
  swe_deep:
    driver: local
    name: swe_deep